version: "3.7"
services:
  solfitest:
    image: "ghcr.io/concertypin/solfibot-backend:${VERSION}"
    restart: always
    env_file:
      - .env
    ports:
      - ${API_SERVER_PORT:-14785}:${API_SERVER_PORT:-14785}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.5
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /data/db
        read_only: false
    restart: always
    ports:
      - "27017:27017"