version: "3.7"
services:
  solfitest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - "${DB_PATH}:/src/db"
    ports:
      - ${API_SERVER_PORT:-14785}:${API_SERVER_PORT:-14785}
