version: "3.7"
services:
  solfitest:
    image: "ghcr.io/concertypin/solfibot-backend:${VERSION}"
    restart: always
    env_file:
      - .env
    volumes:
      - "${DB_PATH}:/src/db"
    ports:
      - ${PORT}:${PORT}